version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: symfony-rest-api.server
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./project/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: DockerfilePhp
    container_name: symfony-rest-api.php
    networks:
      - internal
    volumes:
      - ./project:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log

  db:
    image: postgres:15.2-alpine
    restart: always
    container_name: symfony-rest-api.db
    ports:
      - "8080:5432"
    networks:
      - internal
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

  cache:
    image: redis:7.0-alpine
    restart: always
    container_name: symfony-rest-api.cache
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: symfony-rest-api.mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  internal:
    driver: bridge
